# https://probot.github.io/apps/release-drafter/

name-template: $MAJOR.$MINOR.$PATCH
tag-template:  $MAJOR.$MINOR.$PATCH
change-template: - [#$NUMBER] $TITLE (@$AUTHOR)
no-changes-template: - No changes

categories:
  - title: New features
    label: feature
  - title: Fixed bugs
    label: bug

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

sort-by: merged_at
sort-direction: descending
replacers:
  - search: '/^\s*#+\s/'
    replace: ''
