# https://probot.github.io/apps/release-drafter/

name-template: $PREVIOUS_TAG
tag-template: $PREVIOUS_TAG
change-template: $TITLE (#$NUMBER)
categories:
  - title: Fixed bugs & defects
    label: defect
  - title: New features & improvements 
    label: feature
template: |
  ## Changes

  $CHANGES
  
  ## Contributors
  
  $CONTRIBUTORS
