# https://probot.github.io/apps/settings/

repository:
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true

labels:
  - name: defect
    description:
    color: e99695
    oldname: bug
  - name: question
    description:
    color: bfd4f2
  - name: feature 
    description:
    color: c2e0c6
  - name: help wanted
    description:
    color: fbca04
  - name: on hold
    description:
    color: cccccc
  - name: stale
    description:
    color: 000000

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions: null