# https://probot.github.io/apps/settings/

repository:
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

labels:
  - name: bug
    color: e99695
  - name: documentation
    color: bfd4f2
    oldname: question
  - name: enhancement
    color: c2e0c6
  - name: help wanted
    color: fbca04
  - name: on hold
    color: cccccc
  - name: stale
    color: cccccc