# https://probot.github.io/apps/stale/

daysUntilStale: 60
daysUntilClose: 30
exemptLabels:
  - defect
  - question
  - feature
  - help wanted
  - on hold
staleLabel: stale
markComment: >
  Automatically marked as **stale** because there hasn't been any recent activity. This discussion will be closed in 30 days if no further activity occurs.
closeComment: >
  Automatically **closed** because there hasn't been any activity since this discussion was marked as stale.
